// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_GlELHkRy13ppGCqSuYaAaBdFg5gLRM',
    appId: '1:725567849107:web:d38a28aa072657202bc366',
    messagingSenderId: '725567849107',
    projectId: 'leboncoin-2bd13',
    authDomain: 'leboncoin-2bd13.firebaseapp.com',
    storageBucket: 'leboncoin-2bd13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbN3F9Sz9nR6BNiPRQZTkFU-WKyiiEyE',
    appId: '1:725567849107:android:0bb864be4b7aef672bc366',
    messagingSenderId: '725567849107',
    projectId: 'leboncoin-2bd13',
    storageBucket: 'leboncoin-2bd13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdiYVd6amxV3qWd9fxL2zzNtmS186B_Kg',
    appId: '1:725567849107:ios:62813aa3db7ce1bc2bc366',
    messagingSenderId: '725567849107',
    projectId: 'leboncoin-2bd13',
    storageBucket: 'leboncoin-2bd13.appspot.com',
    iosClientId: '725567849107-c9qifigq9juomqs3i77q6qd4pe3rnp3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.leboncoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdiYVd6amxV3qWd9fxL2zzNtmS186B_Kg',
    appId: '1:725567849107:ios:62813aa3db7ce1bc2bc366',
    messagingSenderId: '725567849107',
    projectId: 'leboncoin-2bd13',
    storageBucket: 'leboncoin-2bd13.appspot.com',
    iosClientId: '725567849107-c9qifigq9juomqs3i77q6qd4pe3rnp3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.leboncoin',
  );
}
